WebApplication13/Models/NhaCungCap.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebApplication13.Models
{
    public class NhaCungCap
    {
        public int NhaCungCapId { get; set; }
        [Required]
        public string TenNhaCungCap { get; set; }
        public string DiaChi { get; set; }
        public LoaiSP LoaiSP { get; set; }
        [Required]
        public int LoaiSPId { get; set; }

        public byte[] Image { get; set; }
        public string Url_Image { get; set; }
        public DateTime NgayTao { get; set; }
        public string ChuThich { get; set; }



        public Boolean Xoa { get; set; }
    }
}

WebApplication13/Controllers/SanPham/NhaCungCapsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication13.Models;

namespace WebApplication13.Controllers
{
    public class NhaCungCapsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        public static int editID;

        static string ImgPath = "/Content/Client/Img/";
        // GET: NhaCungCaps
        public ActionResult Index()
        {
            var NCC = from s in db.NhaCungCaps where s.Xoa == false select s;
            return View(NCC.ToList());
        }

        // GET: NhaCungCaps/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NhaCungCap nhaCungCap = db.NhaCungCaps.Find(id);
            if (nhaCungCap == null)
            {
                return HttpNotFound();
            }
            return View(nhaCungCap);
        }

        // GET: NhaCungCaps/Create
        public ActionResult Create()
        {
            ViewBag.LoaiSPId = new SelectList(db.LoaiSPs, "LoaiSPId", "TenLoai");

            return View();
        }

        // POST: NhaCungCaps/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "NhaCungCapId,TenNhaCungCap,DiaChi, NgayTao,LoaiSPId")] NhaCungCap nhaCungCap, HttpPostedFileBase Image)
        {
            if (Image != null && Image.ContentLength > 0)
            {
                nhaCungCap.Image = new byte[Image.ContentLength];
                Image.InputStream.Read(nhaCungCap.Image, 0, Image.ContentLength);
                string filename = System.IO.Path.GetFileName(Image.FileName);
                string urlImage = Server.MapPath(ImgPath + filename);
                Image.SaveAs(urlImage);
                nhaCungCap.Url_Image = ImgPath + filename;
            }

            if (ModelState.IsValid)
            {
                nhaCungCap.NgayTao = DateTime.Now;
                db.NhaCungCaps.Add(nhaCungCap);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.LoaiSPId = new SelectList(db.LoaiSPs, "LoaiSPId", "TenLoai", nhaCungCap.LoaiSPId);

            return View(nhaCungCap);
        }

        // GET: NhaCungCaps/Edit/5
        public ActionResult Edit(int? id, string strURL)
        {
            editID = id.Value;

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NhaCungCap nhaCungCap = db.NhaCungCaps.Find(id);
            if (nhaCungCap == null)
            {
                return HttpNotFound();
            }
            return View(nhaCungCap);
        }

        // POST: NhaCungCaps/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "NhaCungCapId,TenNhaCungCap,DiaChi,Ngaytao")] NhaCungCap nhaCungCap, HttpPostedFileBase editImage)
        {
            NhaCungCap modifynhaCungCap = db.NhaCungCaps.Find(nhaCungCap.NhaCungCapId);
            if (modifynhaCungCap != null)
            {
                if (editImage != null && editImage.ContentLength > 0)
                {
                    modifynhaCungCap.Image = new byte[editImage.ContentLength];
                    editImage.InputStream.Read(modifynhaCungCap.Image, 0, editImage.ContentLength);
                    string filename = System.IO.Path.GetFileName(editImage.FileName);
                    string urlImage = Server.MapPath(ImgPath + filename);
                    editImage.SaveAs(urlImage);

                    modifynhaCungCap.Url_Image = ImgPath + filename;
                }
            }


            if (ModelState.IsValid)
            {
                db.Entry(modifynhaCungCap).State = EntityState.Modified;
                db.SaveChanges();
                return Redirect(Url.Action("Edit", "Nhacungcaps", new { id = editID }));
            }
            return View(nhaCungCap);
        }

        // GET: NhaCungCaps/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NhaCungCap nhaCungCap = db.NhaCungCaps.Find(id);
            if (nhaCungCap == null)
            {
                return HttpNotFound();
            }
            return View(nhaCungCap);
        }

        // POST: NhaCungCaps/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            NhaCungCap nhaCungCap = db.NhaCungCaps.Find(id);
            nhaCungCap.Xoa = true;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication13/Views/NhaCungCaps/Create.cshtml
@maodel WebApplication13.Models.NhaCungCap

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Layout/_LayoutAdminNew.cshtml";
}



@using (Html.BeginForm("Create", "NhaCungCaps", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="container-fluid">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header card-header-icon card-header-info">
                            <div class="card-icon">
                                <div style="font-size:35px" class="font-weight-bolder">
                                    <i class="material-icons">add_circle_outline</i>
                                    Nhà Cung Cấp
                                </div>
                                <div class="ripple-container"></div>
                            </div>
                        </div>
                        <div class="card-body">
                            <div style="font-size:16px" class="col-md-10 ml-auto mr-5">
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                <div class="row mt-1">
                                    <label class="col-sm-3 col-form-label">Tên Nhà Cung Cấp :</label>
                                    <div class="col-sm-6">
                                        <div class="form-group bmd-form-group">
                                            <input class="form-control" type="text" name="TenNhaCungCap" required="true" aria-required="true">
                                        </div>
                                    </div>
                                </div>
                                <div class="row mt-1">
                                    <label class="col-sm-3 col-form-label">Địa Chỉ :</label>
                                    <div class="col-sm-6">
                                        <div class="form-group bmd-form-group">
                                            <input class="form-control" type="text" name="DiaChi" minlength="5" required="true" aria-required="true">
                                        </div>
                                    </div>
                                </div>
                                <div class="row mt-3">
                                    <label class="col-sm-3 col-form-label">Loại Sản Phẩm :</label>
                                    <div class="col-sm-2">
                                        <div class="form-group bmd-form-group">
                                            @Html.DropDownList("LoaiSPId", null, htmlAttributes: new { @class = "form-control", @style = "text-align:center" })
                                            @Html.ValidationMessageFor(model => model.LoaiSPId, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>
                                <div class="row mt-3">
                                    <label class="col-sm-3 col-form-label">Hình ảnh :</label>
                                    <div class="col-sm-6">
                                        <div class="fileinput fileinput-new text-center" data-provides="fileinput" style="width:200px">
                                            <div class="fileinput-new thumbnail">
                                                <img src="~/content/test/image_placeholder.jfif" alt="...">
                                            </div>
                                            <div class="fileinput-preview fileinput-exists thumbnail"></div>
                                            <div>
                                                <span class="btn btn-rose btn-round btn-file">
                                                    <span class="fileinput-new">Select image</span>
                                                    <span class="fileinput-exists">Change</span>
                                                    <input name="Image" id="Image" type="file">
                                                </span>
                                                <a href="#pablo" class="btn btn-danger btn-round fileinput-exists" data-dismiss="fileinput"><i class="fa fa-times"></i> Remove</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>



                                <div class="form-group mt-4">
                                    <div class="col-md-offset-2 col-md-10 mt-5 mb-5">
                                        <input type="submit" value="Xác Nhận" class="btn btn-outline-danger btn-lg float-right" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

WebApplication13/Views/NhaCungCaps/Delete.cshtml
@model WebApplication13.Models.NhaCungCap

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Layout/_LayoutAdminNew.cshtml";
}

<div class="container-fluid">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header card-header-icon card-header-info">
                        <div class="card-icon">
                            <div style="font-size:35px" class="font-weight-bolder">
                                <i class="material-icons">add_circle_outline</i>
                                Nhà Cung Cấp
                            </div>
                            <div class="ripple-container"></div>
                        </div>
                    </div>
                    <div class="form-horizontal">
                        <div class="card-body">
                            
                            <div style="font-size:18px" class="col-md-10 ml-auto mr-5">
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                <div class="row mt-1">
                                    <label class="col-sm-2 col-form-label"> Tên Nhà C.Cấp :</label>
                                    <div class="col-sm-7">
                                        <div class="form-group bmd-form-group">
                                            @Html.DisplayFor(model => model.TenNhaCungCap, new { htmlAttributes = new { @class = "form-control" } })
                                        </div>
                                    </div>
                                </div>
                                <div class="row mt-1">
                                    <label class="col-sm-2 col-form-label"> Địa Chỉ :</label>
                                    <div class="col-sm-7">
                                        <div class="form-group bmd-form-group">
                                            @Html.DisplayFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                                        </div>
                                    </div>
                                </div>
                                <div class="row mt-1">
                                    <label class="col-sm-2 col-form-label"> Địa Chỉ :</label>
                                    <div class="col-sm-7">
                                        <div class="form-group bmd-form-group">
                                            @Html.DisplayFor(model =>model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group mt-4">
                                    <div class="col-md-offset-2 col-md-10 mt-5 mb-5">
                                        <a class="btn btn-outline-danger btn-lg float-left" href="@Url.Action("Index","NhaCungCaps")"> Trở Về</a>
                                        @using (Html.BeginForm())
                                        {
                                            @Html.AntiForgeryToken()

                                        <div class="form-actions no-color">
                                            <input type="submit" value="Xác Nhận Xoá" class="btn btn-outline-danger btn-lg float-right" />
                                        </div>
                                        }
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

WebApplication13/Views/NhaCungCaps/Details.cshtml
@model WebApplication13.Models.NhaCungCap

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Layout/_LayoutUser.cshtml";
}

<h2>Details</h2>

<div>
    <h4>NhaCungCap</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenNhaCungCap)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenNhaCungCap)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DiaChi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DiaChi)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.NhaCungCapId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebApplication13/Views/NhaCungCaps/Edit.cshtml
@model WebApplication13.Models.NhaCungCap

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Layout/_LayoutAdminNew.cshtml";
}
@using (Html.BeginForm("Edit", "NhaCungCaps", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="container-fluid">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header card-header-icon card-header-info">
                            <div class="card-icon">
                                <div style="font-size:35px" class="font-weight-bolder">
                                    <i class="material-icons">add_circle_outline</i>
                                    Nhà Cung Cấp
                                </div>
                                <div class="ripple-container"></div>
                            </div>
                        </div>
                        <div class="form-horizontal">
                            <div class="card-body">
                                <div style="font-size:18px" class="col-md-10 ml-auto mr-5">
                                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                    @Html.HiddenFor(model => model.NhaCungCapId)
                                    <div class="row mt-1">
                                        <label class="col-sm-2 col-form-label"> Tên Nhà C.Cấp :</label>
                                        <div class="col-sm-7">
                                            <div class="form-group bmd-form-group">
                                                @Html.EditorFor(model => model.TenNhaCungCap, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.TenNhaCungCap, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row mt-1">
                                        <label class="col-sm-2 col-form-label"> Địa Chỉ :</label>
                                        <div class="col-sm-7">
                                            <div class="form-group bmd-form-group">
                                                @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row mt-1">
                                        <label class="col-sm-2 col-form-label">Chú Thích :</label>
                                        <div class="col-sm-7">
                                            <div class="form-group bmd-form-group">
                                                <input class="form-control" type="text" name="MoTa" minlength="5" required="true" aria-required="true">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row mt-1">
                                        <label class="col-sm-2 col-form-label">Hình ảnh :</label>
                                        <div class="col-sm-7">
                                            <div class="fileinput fileinput-new text-center" data-provides="fileinput" style="width:200px">
                                                <div class="fileinput-new thumbnail">
                                                    <img src="@Url.Content(Model.Url_Image)" alt="...">
                                                </div>
                                                <div class="fileinput-preview fileinput-exists thumbnail"></div>
                                                <div>
                                                    <span class="btn btn-rose btn-round btn-file">
                                                        <span class="fileinput-new">Select image</span>
                                                        <span class="fileinput-exists">Change</span>
                                                        <input name="editImage" id="editImage" type="file">
                                                    </span>
                                                    <a href="#pablo" class="btn btn-danger btn-round fileinput-exists" data-dismiss="fileinput"><i class="fa fa-times"></i> Remove</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>



                                    <div class="form-group mt-4">
                                        <div class="col-md-offset-2 col-md-10 mt-5 mb-5">
                                            <a class="btn btn-outline-danger btn-lg float-left" href="@Url.Action("Index","NhaCungCaps")"> Trở Về</a>
                                            <input type="submit" value="Lưu Thay Đổi" class="btn btn-outline-danger btn-lg float-right" />
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

    

WebApplication13/Views/NhaCungCaps/Index.cshtml
@model IEnumerable<WebApplication13.Models.NhaCungCap>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Layout/_LayoutAdminNew.cshtml";
}

<div class="container-fluid">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header card-header-icon card-header-info">
                        <div class="card-icon">
                            <div style="font-size:35px" class="font-weight-bolder">

                                Nhà Cung Cấp
                            </div>
                            <div class="ripple-container"></div>
                        </div>
                    </div>
                    <div class="card-body ml-5" style="padding-right:70px">
                        <div class="table-responsive">
                            <table class="table" style="font-size:18px">
                                <thead class=" text-primary">
                                    <tr>
                                        <th>
                                            Tên Nhà Cung Cấp
                                        </th>
                                        <th>
                                            Địa Chỉ
                                        </th>
                                        <th>
                                            Chú Thích
                                        </th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.TenNhaCungCap)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.DiaChi)
                                            </td>
                                            <td></td>
                                            <td>
                                                <div class="form-group bmd-form-group">
                                                    <a href="@Url.Action("Edit","NhaCungCaps",new { id = item.NhaCungCapId })" class="btn btn-info btn-round" data-original-title="" title="">
                                                        <i class="material-icons">edit</i>
                                                    </a>
                                                    <a href="@Url.Action("Delete","NhaCungCaps",new { id = item.NhaCungCapId })" class="btn btn-danger btn-round" data-original-title="" title="">
                                                        <i class="material-icons">close</i>
                                                    </a>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>