WebApplication13/Models/CuaHang.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebApplication13.Models
{
    public class CuaHang
    {

        public int CuaHangId { get; set; }
        [Required]
        public string TenCuaHang { get; set; }
        public string displayName { get; set; }
        public string DiaChi { get; set; }

        public Boolean Show { get; set; }


    }
}

WebApplication13/Models/DonHang.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace WebApplication13.Models
{
    public class DonHang
    {
        public int DonHangId { get; set; }
        [Required]
        public int SoLuongBan { get; set; }
        public string HinhThucTT { get; set; }
        public float TongTien { get; set; }

        public DateTime NgayMua { get; set; }

        public KhachHang KhachHang { get; set; }
        [Required]
        public int KhachHangId { get; set; }

        public CuaHang CuaHang { get; set; }
        [Required]
        public int CuaHangId { get; set; }
    }
    public class renderView
    {
        public DateTime NgayMua { get; set; }
        public List<DonHang> SLB { get; set; }
    }
}

WebApplication13/Controllers/Bán Hàng__Đơn Hàng/DonHangsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using WebApplication13.Models;

namespace WebApplication13.Controllers.User
{
    public class DonHangsController : Controller
    {

        ApplicationDbContext db = new ApplicationDbContext();

        // GET: DonHangs
        public ActionResult Index()
        {
            var MaCH = User.TenCuaHang();
            var donHangs = (from s in db.DonHangs
                            where s.CuaHangId.ToString() == MaCH.ToString()
                            select s).Include(s => s.KhachHang).ToList();
            return View(donHangs);
        }

        public ActionResult Details(int id)
        {
            var CTDH = (from s in db.CTDonHangs
                        where s.DonhangId == id
                        select s).Include(s => s.SanPham).Include(s => s.DonHang);
            return View(CTDH);
        }
        // GET: DonHangs/Details/5

    }
}

WebApplication13/Views/CuaHang/DSDonHang.cshtml
@model IEnumerable<WebApplication13.Models.CuaHang>
@foreach (var item in Model)
{
    <li class="nav-item ">

        <a class="nav-link" href="@Url.Action("DonHang","CuaHang", new { id = item.CuaHangId })">
            <i class="material-icons">timeline</i>
            <p> Danh Sách Đơn Hàng </p>
        </a>
    </li>
}

WebApplication13/Views/CuaHang/DonHang.cshtml
@model IEnumerable<WebApplication13.Models.DonHang>

@{
    ViewBag.Title = "DonHang";
    Layout = "~/Views/Layout/_LayoutCuaHang.cshtml";
}

<h2>DonHang</h2>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header card-header-icon card-header-info">
                    <div class="card-icon">
                        <div style="font-size:40px" class="font-weight-bolder">
                            Danh Sách Sản Phẩm
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <hr />
                    <div class="material-datatables">
                        <div class="table-responsive">
                            <table id="zero_config" class="table table-striped table-bordered">
                                <thead style="background-color:bisque;font-size:25px " class="text-center">
                                    <tr>
                                        <th>
                                            Mã Đơn Hàng
                                        </th>
                                        <th>
                                            Tên Khách Hàng
                                        </th>
                                        <th>
                                            Số Sản Phẩm
                                        </th>
                                        <th>
                                            Tổng Tiền
                                        </th>
                                        <th>
                                            Ngày Lập
                                        </th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>
                                                @item.DonHangId
                                            </td>
                                            <td>
                                              
                                            </td>
                                            <td class="col-sm-2">
                                                @String.Format("{0:0,0}", item.SoLuongBan)
                                            </td>

                                            <td>
                                                @String.Format("{0:0,0}", item.TongTien)
                                            </td>
                                            <td>
                                                @item.NgayMua
                                            </td>
                                            <td>
                                                <a class="btn btn-outline-primary" href="@Url.Action("Details","DonHangs", new { id = item.DonHangId })">Chi Tiết</a>
                                            </td>

                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

WebApplication13/Views/CuaHang/Index.cshtml
@model WebApplication13.Models.CuaHang
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Layout/_LayoutCuaHang.cshtml";
}

<h2>Index</h2>

@ViewBag.message